version: '3.8'

services:

  db:
    container_name: adhoc-db
    build:
      context: ./dataingest/db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ol_intel
      - POSTGRES_PASSWORD=ol_intel
    volumes:
      - "adhoc_data:/var/lib/postgresql/data/"
  
  tx:
    container_name: adhoc-tx
    build:
      context: ./dataingest
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    environment:
      - DATABASE_URL=postgresql://ol_intel:ol_intel@db:5432/adhoc
    volumes:
      - './dataingest:/usr/src/app'
    depends_on:
      - db

volumes:
  adhoc_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "~/adhoc_vol/"
